CREATE TABLE `admin` (
	`ADMIN_ID` VARCHAR(60) NOT NULL,
	`PASS_WD` VARCHAR(60) NOT NULL,
	`NAME` VARCHAR(60) NOT NULL,
	`EMAIL` VARCHAR(100) NULL DEFAULT NULL,
	`JOIN_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREAT_ID` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`ADMIN_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `cart` (
	`CART_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USERID` VARCHAR(60) NOT NULL,
	`PRODUCT_ID` INT(11) NOT NULL,
	`AMOUNT` VARCHAR(200) NULL DEFAULT NULL,
	`REGIST_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`CART_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `employees` (
	`id` BIGINT(20) NOT NULL,
	`email_address` VARCHAR(255) NOT NULL,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `hibernate_sequence` (
	`next_val` BIGINT(20) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `member` (
	`USERID` VARCHAR(60) NOT NULL,
	`PASSWD` VARCHAR(60) NOT NULL,
	`NAME` VARCHAR(60) NOT NULL,
	`EMAIL` VARCHAR(100) NULL DEFAULT NULL,
	`JOIN_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREA_ID` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`USERID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `product` (
	`PRODUCT_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`PRODUCT_NAME` VARCHAR(60) NOT NULL,
	`PRICE` VARCHAR(100) NOT NULL,
	`DESCRIPTION` VARCHAR(200) NULL DEFAULT NULL,
	`PICTURE_URL` VARCHAR(60) NOT NULL,
	`REGIST_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`PRODUCT_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `tb_board` (
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`PARENT_IDX` INT(11) NULL DEFAULT NULL,
	`TITLE` VARCHAR(100) NOT NULL,
	`CONTENTS` VARCHAR(4000) NOT NULL,
	`HIT_CNT` INT(11) NOT NULL,
	`DEL_GB` VARCHAR(10) NOT NULL DEFAULT 'N',
	`CREA_DTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREA_ID` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`IDX`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `tb_file` (
	`IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`BOARD_IDX` INT(11) NOT NULL,
	`ORIGINAL_FILE_NAME` VARCHAR(260) NOT NULL,
	`STORED_FILE_NAME` VARCHAR(36) NOT NULL,
	`FILE_SIZE` INT(11) NULL DEFAULT NULL,
	`CREA_DTM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREA_ID` VARCHAR(30) NOT NULL,
	`DEL_GB` VARCHAR(1) NOT NULL DEFAULT 'N',
	PRIMARY KEY (`IDX`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `travel` (
	`TRAVEL_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TRAVEL_NAME` VARCHAR(60) NULL DEFAULT NULL,
	`TRAVEL_ADDRESS` VARCHAR(200) NULL DEFAULT NULL,
	`TRAVEL_LATITUDE` VARCHAR(200) NULL DEFAULT NULL,
	`TRAVEL_LONGITUDE` VARCHAR(200) NULL DEFAULT NULL,
	`TRAVEL_DATE` DATETIME NULL DEFAULT NULL,
	`REG_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`UPD_DT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`TRAVEL_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
